messages:
    prefix: '&a!&8>' #You can use this message in any other with %prefix%
    noperms: '%prefix% &cYou do not have permission to do this.' #This is the message used when a player uses a command they do not have access to.
    done: '%prefix% &aDone!' #This message is used when something has been "done".
    urlblocked: '%prefix% &cYou are not allowed to use URLs or IPs in chat.' #This message is used when a player attempts to send a link or an IP.

    clearchat:
        clearline: '&8&m=====&a%player% &7cleared the chat&8&m====='
        clearlineplayer: '&8&m=====&a%player% &7cleared your chat&8&m====='

    mutechat:
        chatismuted: '%prefix% &7Chat is currently &amuted&7!' #This is the message used when a player tries to type when the chat is muted.
        nolongermuted: '%prefix% &7Chat is no longer &amuted&7!' #This is the message used when the chat is no longer muted, it will be broadcasted to everyone.
        isnowmuted: '%prefix% &7Chat is now &amuted&7!' #This is the message used when the chat is now muted, it will be broadcasted to everyone.

    commandblock:
        nocolons: '%prefix% &cYou cannot use colons in commands.' #This message is used when a player attempts to use a command that has colons. For e.g "/essentials:me"
        blockedcommand: '%prefix% &cThat command is blocked'

settings:
    enable:
        clearchat: true
        mutechat: true
        urlblock: true
        commandblock: true


    mutechat:
        blockedcommands:
                - me
                - say


    commandblock:
        blockcolons: true #Should we block the use of ":" in commands? "chat.commandblock.bypass" bypasses this.

        useperworld: false #If set to true, you must set block commands for all worlds, or we will just use the blocked commands in "world". If false, add all blocked commands to "blockedcommands"

        blockedcommands: #This only works if "useperworld" is false.
            #- fly
            #- gamemode

        world: #This only works if "userperworld" is true.
            #- fly
            #- gamemode

        exampleworld:
            #- fly
            #- gamemode