name: Chat
version: 0.1
main: me.tekoh.chat.Core
description: Just another Chat plugin

commands:
    mutechat:
        usage: /<command>
        description: Toggle whether or not the chat is muted.
        aliases: [mc, mchat, mutec]

    clearchat:
        usage: /<command>
        description: Clear the chat.
        aliases: [cc, clearc, cchat]

    chat:
        usage: /<command>
        description: Reload the config